### ISSUE TITLE
Integrationtests setup

### ISSUE THREAD

**Issue by Zethson** [qbicsoftware/parent-poms#32]
Huhu,

we could add a setup for integration tests. Integration tests are often times slow and are communicating with databases, writing files and more. A separation of different test setups would allow us to run either just the unit tests or all integration tests. 
See: https://semaphoreci.com/community/tutorials/how-to-split-junit-tests-in-a-continuous-integration-environment

This would allow us to split normal unit tests into the goal
mvn test
and lengthy integration tests into
mvn integration-test

`            
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <groups>life.qbic.testConfigurations.IntegrationTest</groups>
                </configuration>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>verify</id>
                        <goals>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

mvn test will then only run the unit tests (blablaTest)
mvn integration-test will only run integration tests (blablaIT)

It's likely that we would need to adapt our travis build. We can discuss whether or not we want to always run integration tests on travis.

Moreover, we could incorporate Interfaces into our cookiecutter templates to add groups to our tests which also allows us to only run subsets of the tests.

@Category({IntegrationTest.class, Slow.class})

for example.

**Comment by Zethson** [comment]
So there is already an integration test setup ;)

Might be a good idea to add a dummy in the cookiecutter though!

**Comment by chahuistle** [comment]
Forgot to reply to your comment. So, I added some sample integration tests in the cookiecutters that contain some code. [This commit](https://github.com/qbicsoftware/cookiecutter-templates-cli/commit/e477474e041c17b98fb3ca73eb6922c8cd21902e) added the following templates for integration tests (among other changes):

  * `./cookiecutters/cli/{{ cookiecutter.artifact_id }}/src/test/java/life/qbic/cli/{{ cookiecutter.main_class_prefix }}IntegrationTest.java`
  * `./cookiecutters/service/{{ cookiecutter.artifact_id }}/src/test/java/life/qbic/service/{{ cookiecutter.main_class_prefix }}ServiceIntegrationTest.java`
  * `./cookiecutters/portlet/{{ cookiecutter.artifact_id }}/src/test/java/life/qbic/portal/portlet/{{ cookiecutter.main_class_prefix }}PortletIntegrationTest.java`
  * `./cookiecutters/gui/{{ cookiecutter.artifact_id }}/src/test/java/life/qbic/gui/{{ cookiecutter.main_class_prefix }}IntegrationTest.java`

There is no template code for the `generic-lib` cookiecutter, though. Since a generic library is "freestyle" coding, I thought that adding a sample class and sample tests would be a bad idea: at some point, our repositories would be full of `DummyAlgorithm.java`, `DummyAlgorithmTest.java` and `DummyAlgorithmIntegrationTest.java` files.
